name: ci

on:
  push:
    branches: [ main ]
    tags:
    - '*'


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v2

      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/przemyslawbajda/fibonacci_calculator
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=docker.io/przemyslawbajda/fibonacci_calculator:cache
          cache-to: type=registry,ref=docker.io/przemyslawbajda/fibonacci_calculator:cache
          platforms: linux/arm64,linux/amd64
          context: ./
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}